version: "3.8"

services:
  app:
    container_name: recipesapi-app
    image: recipesapi
    build:
      args:
        user: user
        uid: 1000
      context: ./docker-compose/php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  database:
    container_name: recipesapi-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - recipesdb:/var/lib/postgresql/data

  pgadmin:
    container_name: recipesapi-dbadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - dbadmin:/var/lib/pgadmin
    depends_on:
      - database

  nginx:
    container_name: recipesapi-nginx
    image: nginx
    build:
      context: ./docker-compose/nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/

volumes:
  recipesdb:
  dbadmin:
